{% set name = "h3" %}
{% set version = "3.7.4" %}

package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8edf5a546b31afdcd801b60448ea890ce1ff418fb784335e1329519f13aa85e

build:
  number: 1
  skip: true  # [python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                  # [unix]
  host:
    - python
    - pip
    - scikit-build
    - cython
  run:
    - python
    - numpy

test:
  imports:
    - h3

about:
  home: https://github.com/uber/h3-py.git
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python bindings for H3, a hierarchical hexagonal geospatial indexing system developed by Uber Technologies
  dev_url: https://github.com/uber/h3-py.git

extra:
  recipe-maintainers:
    - mxr-conda
    - bubblyorca
    - geoHeil
